using System;
using System.Text;

namespace Colin.Core.Graphics.Visual.Particle.Rendering
{
  /// <summary>
  /// 预编译着色器字节 (嵌入资源): ParticleRender.fx 经 mgfxc /Profile:DirectX_11 编译的
  /// MGFX 二进制, Base64 存储 —— 运行时零依赖; 亦可经 <see cref="ParticleRenderEffect"/>
  /// 的 EffectProcessor 进程内编译从嵌入源码生成.
  /// </summary>
  internal static class ParticleCompiledShaders
  {
    public const int RenderEffectLength = 2612;

    public const string RenderEffectBase64 =
    "TUdGWAoB/wPo8wEAAAAAUAAEAAAAAAAAAAAAAQAAAEAAAgAAAEQAAwAAAEgAAgAAAAB8AQAARFhCQ0AZrTJ808VlWUyfmsmjz44B" +
    "AAAAfAEAAAMAAAAsAAAAoAAAANQAAABJU0dObAAAAAMAAAAIAAAAUAAAAAAAAAABAAAAAwAAAAAAAAAPAAAAXAAAAAAAAAAAAAAA" +
    "AwAAAAEAAAADAwAAZQAAAAAAAAAAAAAAAwAAAAIAAAAPDwAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAQ09MT1IAq09TR04sAAAAAQAA" +
    "AAgAAAAgAAAAAAAAAAAAAAADAAAAAAAAAA8AAABTVl9UYXJnZXQAq6tTSEVYoAAAAFAAAAAoAAAAaggAAVoAAAMAYBAAAAAAAFgY" +
    "AAQAcBAAAAAAAFVVAABiEAADMhAQAAEAAABiEAAD8hAQAAIAAABlAAAD8iAQAAAAAABoAAACAQAAAEUAAIvCAACAQ1UVAPIAEAAA" +
    "AAAARhAQAAEAAABGfhAAAAAAAABgEAAAAAAAOAAAB/IgEAAAAAAARg4QAAAAAABGHhAAAgAAAD4AAAEBAAAAAAAEAAABNAcAAERY" +
    "QkNP5XlO1Ab3SKwRAwUbIVsKAQAAADQHAAADAAAALAAAAJgAAAAMAQAASVNHTmQAAAADAAAACAAAAFAAAAAAAAAAAAAAAAMAAAAA" +
    "AAAAAwMAAFkAAAAAAAAAAAAAAAMAAAABAAAAAwMAAFkAAAABAAAAAAAAAAMAAAACAAAAAQEAAFBPU0lUSU9OAFRFWENPT1JEAKur" +
    "T1NHTmwAAAADAAAACAAAAFAAAAAAAAAAAQAAAAMAAAAAAAAADwAAAFwAAAAAAAAAAAAAAAMAAAABAAAAAwwAAGUAAAAAAAAAAAAA" +
    "AAMAAAACAAAADwAAAFNWX1BPU0lUSU9OAFRFWENPT1JEAENPTE9SAKtTSEVYIAYAAFAAAQCIAQAAaggAAVkAAARGjiAAAAAAAAUA" +
    "AABaAAADAGAQAAEAAABYGAAEAHAQAAEAAABVVQAAXwAAAzIQEAAAAAAAXwAAAzIQEAABAAAAXwAAAxIQEAACAAAAZwAABPIgEAAA" +
    "AAAAAQAAAGUAAAMyIBAAAQAAAGUAAAPyIBAAAgAAAGgAAAIGAAAAAAAABxIAEAAAAAAAChAQAAIAAAABQAAAAAAAPw4AAAgSABAA" +
    "AAAAAAoAEAAAAAAACoAgAAAAAAAEAAAANgAABSIAEAAAAAAAAUAAAAAAAD9IAACNwgAAgENVFQByABAAAQAAAEYAEAAAAAAARnsQ" +
    "AAEAAAAAYBAAAQAAAAFAAAAAAAAAHQAAB0IAEAABAAAAAUAAAAAAAAAqABAAAQAAAB8ABAMqABAAAQAAADYAAAjyIBAAAAAAAAJA" +
    "AAAAAAAAAAAAAAAAAMAAAAAANgAACPIgEAACAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAA2AAAIMiAQAAEAAAACQAAAAAAAAAAAAAAA" +
    "AAAAAAAAAD4AAAEVAAABNgAACMIAEAAAAAAAAkAAAAAAAAAAAAAAzczMPZqZmT5IAACNwgAAgENVFQDyABAAAgAAAIYAEAAAAAAA" +
    "Rn4QAAEAAAAAYBAAAQAAAAFAAAAAAAAASAAAjcIAAIBDVRUA8iAQAAIAAADGABAAAAAAAEZ+EAABAAAAAGAQAAEAAAABQAAAAAAA" +
    "ADYAAAhiABAAAAAAAAJAAAAAAAAAMzMzP2ZmZj8AAAAASAAAjcIAAIBDVRUAIgAQAAAAAABGABAAAAAAAEZ+EAABAAAAAGAQAAEA" +
    "AAABQAAAAAAAAEgAAI3CAACAQ1UVABIAEAAAAAAAhgAQAAAAAAAWfhAAAQAAAABgEAABAAAAAUAAAAAAAAAPAAAHQgAQAAAAAADm" +
    "ChAAAgAAAOYKEAACAAAASwAABUIAEAAAAAAAKgAQAAAAAAAxAAAKkgAQAAAAAAACQAAAAAAAPwAAAAAAAAAAF7fROAYIEAAAAAAA" +
    "DgAAB8IAEAABAAAApg4QAAIAAACmChAAAAAAADcAAAwyABAAAwAAAPYPEAAAAAAA5goQAAEAAAACQAAAAACAPwAAAAAAAAAAAAAA" +
    "ADgAAAhCABAAAAAAACoAEAAAAAAAGoAgAAAAAAAEAAAAMwAACEIAEAAAAAAAKgAQAAAAAAAqgCAAAAAAAAQAAAA0AAAKogAQAAAA" +
    "AABWBRAAAAAAAAJAAAAAAAAAF7fROAAAAAAAAIA/MgAACUIAEAAAAAAACgAQAAEAAAA6ABAAAAAAACoAEAAAAAAAOAAAB0IAEAAA" +
    "AAAAKgAQAAAAAAAKEBAAAAAAADIAAAnCABAAAAAAAAYEEAADAAAApgoQAAAAAAAGBBAAAgAAADgAAAdSABAAAQAAAAYAEAABAAAA" +
    "VhQQAAAAAAA2AAAGQgAQAAMAAAAaABCAQQAAAAMAAAAyAAAJwgAQAAAAAACmAhAAAwAAAAYAEAABAAAApg4QAAAAAABNAAAHEgAQ" +
    "AAMAAAASABAABAAAABoAEAABAAAAOAAAByIAEAAAAAAAGgAQAAAAAAAqABAAAQAAADgAAAciABAAAQAAAAoAEAABAAAACgAQAAMA" +
    "AAAyAAAKEgAQAAUAAAAaABAAAAAAAAoAEAAEAAAAGgAQgEEAAAABAAAAOAAABxIAEAABAAAACgAQAAEAAAAKABAABAAAADIAAAki" +
    "ABAABQAAABoAEAAAAAAACgAQAAMAAAAKABAAAQAAAAAAAAcyABAAAQAAAEYAEAACAAAARgAQAAUAAAA3AAAJMgAQAAAAAAAGABAA" +
    "AAAAAOYKEAAAAAAARgAQAAEAAAA2AAAFQgAQAAAAAAABQAAAAACAPxAAAAgSIBAAAAAAAEYCEAAAAAAARoMgAAAAAAAAAAAAEAAA" +
    "CCIgEAAAAAAARgIQAAAAAABGgyAAAAAAAAEAAAAQAAAIQiAQAAAAAABGAhAAAAAAAEaDIAAAAAAAAgAAABAAAAiCIBAAAAAAAEYC" +
    "EAAAAAAARoMgAAAAAAADAAAANgAABTIgEAABAAAARhAQAAEAAAA+AAABAQABAQAABQEAAAYAAAACAwlUcmFuc2Zvcm0AAAAAAAQE" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMI" +
    "Q2FwYWNpdHkAAAAAAAEBAAAAAAAAAAAAAAAAAAMNU3RyZXRjaEZhY3RvcgAAAAAAAQEAAAAAAAAAAAAAAAAAAxBNYXhTdHJldGNo" +
    "TGVuZ3RoAAAAAAABAQAAAAAAAAAAAAAAAAMHDVNwcml0ZVRleHR1cmUAAAAAAAAAAAAAAAAAAAADBwtEYXRhVGV4dHVyZQAAAAAA" +
    "AAAAAAAAAAAAAAEAAAARUGFydGljbGVSZW5kZXJpbmcAAAAAAQAAAAJQMAAAAAABAAAAAAAAAAAAAE1HRlg=";
  }
}
