// <auto-generated>由 ParticleRender.fx 生成, 请勿手改.</auto-generated>
namespace Particle.Rendering
{
  /// <summary>粒子渲染着色器的 HLSL 源码 (嵌入常量, 供运行时编译回退使用).</summary>
  internal static class ParticleShaderSource
  {
    public const string RenderEffectSource =
@"// =====================================================================
// 粒子渲染着色器 (纹理粒子版, MonoGame Effect / DirectX_11):
// 粒子状态存于""数据纹理"" (宽 = 容量, 高 = 5 行 RGBA32F, 逐行对应 Particle 的 5 个 float4),
// 实例流只携带槽位 ID, 顶点着色器按 ID 做纹素取样展开四边形 —— 与老 GpuParticle 思路一致.
// 双流实例化: 流 0 = 四边形角点模板, 流 1 = 槽位 ID.
// =====================================================================

Texture2D<float4> SpriteTexture : register(t0);
sampler SpriteTextureSampler : register(s0);

// 粒子数据纹理: [列 = 槽位, 行 = 数据段].
Texture2D<float4> DataTexture : register(t1);
SamplerState DataSampler : register(s1)
{
    Filter = Point;
    AddressU = Clamp;
    AddressV = Clamp;
};

// 世界坐标 -> 裁剪空间 的完整变换 (View * Projection).
float4x4 Transform;
// 数据纹理宽度 (= 粒子容量), 用于纹素中心对齐.
float Capacity;
// 速度拉伸系数 (秒): 拉伸长度增量 = |速度| * StretchFactor.
float StretchFactor;
// 速度拉伸最大长度 (像素).
float MaxStretchLength;

// ---- 流 0: 四边形角点 (三角带 4 顶点, ±0.5) ----
// ---- 流 1: 槽位 ID (每实例一个) ----
struct VertexShaderInput
{
    float2 Corner : POSITION0;
    float2 Uv : TEXCOORD0;
    float ID : TEXCOORD1;
};

struct VertexShaderOutput
{
    float4 Position : SV_POSITION;
    float2 Uv : TEXCOORD0;
    float4 Color : COLOR0;
};

VertexShaderOutput MainVS(VertexShaderInput input)
{
    VertexShaderOutput output;

    // —— 按槽位取样粒子数据 (纹素中心对齐; 行: 0=位置速度, 1=颜色, 2=尺寸旋转年龄生命, 3=杂项, 4=基准) ——
    float u = (input.ID + 0.5f) / Capacity;
    float4 posVel = DataTexture.SampleLevel(DataSampler, float2(u, 0.1f), 0);
    float4 color = DataTexture.SampleLevel(DataSampler, float2(u, 0.3f), 0);
    float4 sizeRotAgeLife = DataTexture.SampleLevel(DataSampler, float2(u, 0.5f), 0);
    float4 misc = DataTexture.SampleLevel(DataSampler, float2(u, 0.7f), 0);
    float4 extra = DataTexture.SampleLevel(DataSampler, float2(u, 0.9f), 0);

    float life = sizeRotAgeLife.w;
    if (life <= 0)
    {
        // 死亡槽位: 退化四边形 (全部顶点重合于裁剪空间外).
        output.Position = float4(0, 0, -2, 0);
        output.Uv = float2(0, 0);
        output.Color = float4(0, 0, 0, 0);
        return output;
    }

    float2 position = posVel.xy;
    float2 velocity = posVel.zw;
    float size = sizeRotAgeLife.x;
    float rotation = sizeRotAgeLife.y;
    float aspect = max(misc.y, 0.0001);
    float stretched = extra.y;
    float2 worldPosition;

    if (stretched > 0.5)
    {
        // —— 速度拉伸: 沿速度方向展开, 长度 = 尺寸 * 长宽比 + |速度| * 系数 (封顶) ——
        float speed = length(velocity);
        float2 dir = speed > 0.0001 ? velocity / speed : float2(1, 0);
        float stretchLength = min(speed * StretchFactor, MaxStretchLength);
        float length = size * max(aspect, 1) + stretchLength;
        float thickness = size;

        float2 perp = float2(-dir.y, dir.x);
        worldPosition = position
            + dir * (input.Corner.x * length)
            + perp * (input.Corner.y * thickness);
    }
    else
    {
        // —— 普通公告牌: 按粒子自身旋转角展开 ——
        float c = cos(rotation);
        float s = sin(rotation);
        float2 scaled = float2(input.Corner.x * size * aspect, input.Corner.y * size);
        worldPosition = position + float2(scaled.x * c - scaled.y * s, scaled.x * s + scaled.y * c);
    }

    output.Position = mul(float4(worldPosition, 0, 1), Transform);
    output.Uv = input.Uv;
    output.Color = color;
    return output;
}

float4 MainPS(VertexShaderOutput input) : COLOR
{
    float4 texel = SpriteTexture.Sample(SpriteTextureSampler, input.Uv);
    return texel * input.Color;
}

technique ParticleRendering
{
    pass P0
    {
        VertexShader = compile vs_5_0 MainVS();
        PixelShader = compile ps_5_0 MainPS();
    }
};
";
  }
}
