using System;
using System.Text;

namespace Particle.Rendering
{
  /// <summary>
  /// 预编译着色器字节 (嵌入资源): ParticleRender.fx 经 mgfxc /Profile:DirectX_11 编译的
  /// MGFX 二进制, Base64 存储 —— 运行时无需外部文件即可构建粒子渲染管线.
  /// <br>若源码 (ParticleRender.fx) 被修改, 可用 mgfxc 重新编译后替换本文件中的字符串,
  /// 或交由 <see cref="ParticleRenderEffect"/> 的运行时编译回退自动完成.</br>
  /// </summary>
  internal static class ParticleCompiledShaders
  {
    /// <summary>粒子渲染 Effect (MGFX / DirectX_11) 的字节长度.</summary>
    public const int RenderEffectLength = 2293;

    /// <summary>粒子渲染 Effect (MGFX / DirectX_11) 的 Base64 内容.</summary>
    public const string RenderEffectBase64 =
    "TUdGWAoB6gcA3wEAAAAAUAADAAAAAAAAAAAAAQAAAEAAAgAAAEQAAgAAAAB8AQAARFhCQ0AZrTJ808VlWUyfmsmjz44BAAAAfAEA" +
    "AAMAAAAsAAAAoAAAANQAAABJU0dObAAAAAMAAAAIAAAAUAAAAAAAAAABAAAAAwAAAAAAAAAPAAAAXAAAAAAAAAAAAAAAAwAAAAEA" +
    "AAADAwAAZQAAAAAAAAAAAAAAAwAAAAIAAAAPDwAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAQ09MT1IAq09TR04sAAAAAQAAAAgAAAAg" +
    "AAAAAAAAAAAAAAADAAAAAAAAAA8AAABTVl9UYXJnZXQAq6tTSEVYoAAAAFAAAAAoAAAAaggAAVoAAAMAYBAAAAAAAFgYAAQAcBAA" +
    "AAAAAFVVAABiEAADMhAQAAEAAABiEAAD8hAQAAIAAABlAAAD8iAQAAAAAABoAAACAQAAAEUAAIvCAACAQ1UVAPIAEAAAAAAARhAQ" +
    "AAEAAABGfhAAAAAAAABgEAAAAAAAOAAAB/IgEAAAAAAARg4QAAAAAABGHhAAAgAAAD4AAAEBAAAAAAADAAABPAYAAERYQkPbZdGg" +
    "8jiWSblhXYm56dRwAQAAADwGAAADAAAALAAAAPwAAABwAQAASVNHTsgAAAAHAAAACAAAALAAAAAAAAAAAAAAAAMAAAAAAAAAAwMA" +
    "ALkAAAAAAAAAAAAAAAMAAAABAAAAAwMAAMIAAAAAAAAAAAAAAAMAAAACAAAADw8AAMIAAAABAAAAAAAAAAMAAAADAAAADw8AALkA" +
    "AAABAAAAAAAAAAMAAAAEAAAADwsAALkAAAACAAAAAAAAAAMAAAAFAAAADwIAALkAAAADAAAAAAAAAAMAAAAGAAAADwIAAFBPU0lU" +
    "SU9OAFRFWENPT1JEAENPTE9SAE9TR05sAAAAAwAAAAgAAABQAAAAAAAAAAEAAAADAAAAAAAAAA8AAABcAAAAAAAAAAAAAAADAAAA" +
    "AQAAAAMMAABlAAAAAAAAAAAAAAADAAAAAgAAAA8AAABTVl9QT1NJVElPTgBURVhDT09SRABDT0xPUgCrU0hFWMQEAABQAAEAMQEA" +
    "AGoIAAFZAAAERo4gAAAAAAAFAAAAXwAAAzIQEAAAAAAAXwAAAzIQEAABAAAAXwAAA/IQEAACAAAAXwAAA/IQEAADAAAAXwAAA7IQ" +
    "EAAEAAAAXwAAAyIQEAAFAAAAXwAAAyIQEAAGAAAAZwAABPIgEAAAAAAAAQAAAGUAAAMyIBAAAQAAAGUAAAPyIBAAAgAAAGgAAAIF" +
    "AAAAHQAABxIAEAAAAAAAAUAAAAAAAAA6EBAABAAAAB8ABAMKABAAAAAAADYAAAjyIBAAAAAAAAJAAAAAAAAAAAAAAAAAAMAAAAAA" +
    "NgAACPIgEAACAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAA2AAAIMiAQAAEAAAACQAAAAAAAAAAAAAAAAAAAAAAAAD4AAAEVAAABMQAA" +
    "BxIAEAAAAAAAAUAAAAAAAD8aEBAABgAAAA8AAAciABAAAAAAAOYaEAACAAAA5hoQAAIAAABLAAAFIgAQAAAAAAAaABAAAAAAADEA" +
    "AAdCABAAAAAAAAFAAAAXt9E4GgAQAAAAAAAOAAAHMgAQAAEAAADmGhAAAgAAAFYFEAAAAAAANwAADDIAEAABAAAApgoQAAAAAABG" +
    "ABAAAQAAAAJAAAAAAIA/AAAAAAAAAAAAAAAAOAAACCIAEAAAAAAAGgAQAAAAAAAKgCAAAAAAAAQAAAAzAAAIIgAQAAAAAAAaABAA" +
    "AAAAABqAIAAAAAAABAAAADQAAArCABAAAAAAAFYVEAAFAAAAAkAAAAAAAAAAAAAAF7fROAAAgD8yAAAJIgAQAAAAAAAKEBAABAAA" +
    "ADoAEAAAAAAAGgAQAAAAAAA4AAAHIgAQAAAAAAAaABAAAAAAAAoQEAAAAAAAMgAACaIAEAAAAAAABgQQAAEAAABWBRAAAAAAAAYU" +
    "EAACAAAAOAAABzIAEAACAAAAFhUQAAAAAAAGEBAABAAAADYAAAZCABAAAQAAABoAEIBBAAAAAQAAADIAAAmiABAAAAAAAKYCEAAB" +
    "AAAABgAQAAIAAABWDRAAAAAAAE0AAAcSABAAAQAAABIAEAADAAAAGhAQAAQAAAA4AAAHQgAQAAAAAAAqABAAAAAAABoAEAACAAAA" +
    "OAAAByIAEAABAAAACgAQAAEAAAAKABAAAgAAADIAAAoSABAABAAAACoAEAAAAAAACgAQAAMAAAAaABCAQQAAAAEAAAA4AAAHIgAQ" +
    "AAEAAAAKABAAAgAAAAoAEAADAAAAMgAACSIAEAAEAAAAKgAQAAAAAAAKABAAAQAAABoAEAABAAAAAAAABzIAEAABAAAARgAQAAQA" +
    "AABGEBAAAgAAADcAAAkyABAAAAAAAAYAEAAAAAAA1gUQAAAAAABGABAAAQAAADYAAAVCABAAAAAAAAFAAAAAAIA/EAAACBIgEAAA" +
    "AAAARgIQAAAAAABGgyAAAAAAAAAAAAAQAAAIIiAQAAAAAABGAhAAAAAAAEaDIAAAAAAAAQAAABAAAAhCIBAAAAAAAEYCEAAAAAAA" +
    "RoMgAAAAAAACAAAAEAAACIIgEAAAAAAARgIQAAAAAABGgyAAAAAAAAMAAAA2AAAF8iAQAAIAAABGHhAAAwAAADYAAAUyIBAAAQAA" +
    "AEYQEAABAAAAPgAAAQABAAAEAAAAAgMJVHJhbnNmb3JtAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDVN0cmV0Y2hGYWN0b3IAAAAAAAEBAAAAAAAAAAAAAAAAAAMQ" +
    "TWF4U3RyZXRjaExlbmd0aAAAAAAAAQEAAAAAAAAAAAAAAAADBw1TcHJpdGVUZXh0dXJlAAAAAAAAAAAAAAAAAAAAAQAAABFQYXJ0" +
    "aWNsZVJlbmRlcmluZwAAAAABAAAAAlAwAAAAAAEAAAAAAAAAAAAATUdGWA==";
  }
}
