using System;
using System.Text;

namespace Particle.Slash
{
  /// <summary>
  /// 预编译着色器字节 (嵌入资源): SlashRender.fx 经 mgfxc /Profile:DirectX_11 编译的
  /// MGFX 二进制 —— 运行时零依赖; 亦可经 <see cref="SlashRenderEffect"/> 的
  /// EffectProcessor 进程内编译从嵌入源码生成.
  /// </summary>
  internal static class SlashCompiledShaders
  {
    public const int RenderEffectLength = 1506;

    public const string RenderEffectBase64 =
    "TUdGWAoBAWX8EQEAAAAAYAADAAAAAAAAAAAAAQAAAEAAAgAAAFAAAgAAAAA8AgAARFhCQ8IAShDgTB1e739674IWjkcBAAAAPAIA" +
    "AAMAAAAsAAAAoAAAANQAAABJU0dObAAAAAMAAAAIAAAAUAAAAAAAAAABAAAAAwAAAAAAAAAPAAAAXAAAAAAAAAAAAAAAAwAAAAEA" +
    "AAADAwAAZQAAAAAAAAAAAAAAAwAAAAIAAAAPDwAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAQ09MT1IAq09TR04sAAAAAQAAAAgAAAAg" +
    "AAAAAAAAAAAAAAADAAAAAAAAAA8AAABTVl9UYXJnZXQAq6tTSEVYYAEAAFAAAABYAAAAaggAAVkAAARGjiAAAAAAAAYAAABaAAAD" +
    "AGAQAAAAAABYGAAEAHAQAAAAAABVVQAAYhAAAzIQEAABAAAAYhAAA/IQEAACAAAAZQAAA/IgEAAAAAAAaAAAAgEAAAAAAAAHEgAQ" +
    "AAAAAAAaEBAAAQAAAAFAAAAAAAC/MgAACiIAEAAAAAAACgAQAAAAAAAqgCAAAAAAAAQAAAABQAAAAAAAPzIAAAsSABAAAAAAAAoQ" +
    "EAABAAAACoAgAAAAAAAEAAAAGoAgAAAAAAAEAAAARQAAi8IAAIBDVRUA8gAQAAAAAABGABAAAAAAAEZ+EAAAAAAAAGAQAAAAAAA4" +
    "AAAH8gAQAAAAAABGDhAAAAAAAEYeEAACAAAAOAAACPIAEAAAAAAARg4QAAAAAABGjiAAAAAAAAUAAAA4AAAI8iAQAAAAAABGDhAA" +
    "AAAAAPaPIAAAAAAABAAAAD4AAAEBAAAAAAADAQAAAVwCAABEWEJDhkK9q8Dv79bOB8/+hZDonwEAAABcAgAAAwAAACwAAACcAAAA" +
    "EAEAAElTR05oAAAAAwAAAAgAAABQAAAAAAAAAAAAAAADAAAAAAAAAAMDAABZAAAAAAAAAAAAAAADAAAAAQAAAAMDAABiAAAAAAAA" +
    "AAAAAAADAAAAAgAAAA8PAABQT1NJVElPTgBURVhDT09SRABDT0xPUgBPU0dObAAAAAMAAAAIAAAAUAAAAAAAAAABAAAAAwAAAAAA" +
    "AAAPAAAAXAAAAAAAAAAAAAAAAwAAAAEAAAADDAAAZQAAAAAAAAAAAAAAAwAAAAIAAAAPAAAAU1ZfUE9TSVRJT04AVEVYQ09PUkQA" +
    "Q09MT1IAq1NIRVhEAQAAUAABAFEAAABqCAABWQAABEaOIAAAAAAABAAAAF8AAAMyEBAAAAAAAF8AAAMyEBAAAQAAAF8AAAPyEBAA" +
    "AgAAAGcAAATyIBAAAAAAAAEAAABlAAADMiAQAAEAAABlAAAD8iAQAAIAAABoAAACAQAAADYAAAUyABAAAAAAAEYQEAAAAAAANgAA" +
    "BUIAEAAAAAAAAUAAAAAAgD8QAAAIEiAQAAAAAABGAhAAAAAAAEaDIAAAAAAAAAAAABAAAAgiIBAAAAAAAEYCEAAAAAAARoMgAAAA" +
    "AAABAAAAEAAACEIgEAAAAAAARgIQAAAAAABGgyAAAAAAAAIAAAAQAAAIgiAQAAAAAABGAhAAAAAAAEaDIAAAAAAAAwAAADYAAAUy" +
    "IBAAAQAAAEYQEAABAAAANgAABfIgEAACAAAARh4QAAIAAAA+AAABAAEAAAQAAAACAwlUcmFuc2Zvcm0AAAAAAAQEAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQMLVXZUcmFuc2Zv" +
    "cm0AAAAAAAEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQMJTGF5ZXJUaW50AAAAAAABBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAMHDVNwcml0ZVRleHR1cmUAAAAAAAAAAAAAAAAAAAABAAAADlNsYXNoUmVuZGVyaW5nAAAAAAEAAAACUDAAAAAAAQAAAAAAAAAA" +
    "AABNR0ZY";
  }
}
