using System;
using System.Text;

namespace Particle.Slash
{
  /// <summary>
  /// 预编译着色器字节 (嵌入资源): SlashRender.fx 经 mgfxc /Profile:DirectX_11 编译的
  /// MGFX 二进制 —— 运行时零依赖; 亦可经 <see cref="SlashRenderEffect"/> 的
  /// EffectProcessor 进程内编译从嵌入源码生成.
  /// </summary>
  internal static class SlashCompiledShaders
  {
    public const int RenderEffectLength = 1213;

    public const string RenderEffectBase64 =
    "TUdGWAoBcE79/gEAAAAAQAABAAAAAAAAAAAAAgAAAAB8AQAARFhCQ0AZrTJ808VlWUyfmsmjz44BAAAAfAEAAAMAAAAsAAAAoAAA" +
    "ANQAAABJU0dObAAAAAMAAAAIAAAAUAAAAAAAAAABAAAAAwAAAAAAAAAPAAAAXAAAAAAAAAAAAAAAAwAAAAEAAAADAwAAZQAAAAAA" +
    "AAAAAAAAAwAAAAIAAAAPDwAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAQ09MT1IAq09TR04sAAAAAQAAAAgAAAAgAAAAAAAAAAAAAAAD" +
    "AAAAAAAAAA8AAABTVl9UYXJnZXQAq6tTSEVYoAAAAFAAAAAoAAAAaggAAVoAAAMAYBAAAAAAAFgYAAQAcBAAAAAAAFVVAABiEAAD" +
    "MhAQAAEAAABiEAAD8hAQAAIAAABlAAAD8iAQAAAAAABoAAACAQAAAEUAAIvCAACAQ1UVAPIAEAAAAAAARhAQAAEAAABGfhAAAAAA" +
    "AABgEAAAAAAAOAAAB/IgEAAAAAAARg4QAAAAAABGHhAAAgAAAD4AAAEBAAAAAAABAAABXAIAAERYQkOGQr2rwO/v1s4Hz/6FkOif" +
    "AQAAAFwCAAADAAAALAAAAJwAAAAQAQAASVNHTmgAAAADAAAACAAAAFAAAAAAAAAAAAAAAAMAAAAAAAAAAwMAAFkAAAAAAAAAAAAA" +
    "AAMAAAABAAAAAwMAAGIAAAAAAAAAAAAAAAMAAAACAAAADw8AAFBPU0lUSU9OAFRFWENPT1JEAENPTE9SAE9TR05sAAAAAwAAAAgA" +
    "AABQAAAAAAAAAAEAAAADAAAAAAAAAA8AAABcAAAAAAAAAAAAAAADAAAAAQAAAAMMAABlAAAAAAAAAAAAAAADAAAAAgAAAA8AAABT" +
    "Vl9QT1NJVElPTgBURVhDT09SRABDT0xPUgCrU0hFWEQBAABQAAEAUQAAAGoIAAFZAAAERo4gAAAAAAAEAAAAXwAAAzIQEAAAAAAA" +
    "XwAAAzIQEAABAAAAXwAAA/IQEAACAAAAZwAABPIgEAAAAAAAAQAAAGUAAAMyIBAAAQAAAGUAAAPyIBAAAgAAAGgAAAIBAAAANgAA" +
    "BTIAEAAAAAAARhAQAAAAAAA2AAAFQgAQAAAAAAABQAAAAACAPxAAAAgSIBAAAAAAAEYCEAAAAAAARoMgAAAAAAAAAAAAEAAACCIg" +
    "EAAAAAAARgIQAAAAAABGgyAAAAAAAAEAAAAQAAAIQiAQAAAAAABGAhAAAAAAAEaDIAAAAAAAAgAAABAAAAiCIBAAAAAAAEYCEAAA" +
    "AAAARoMgAAAAAAADAAAANgAABTIgEAABAAAARhAQAAEAAAA2AAAF8iAQAAIAAABGHhAAAgAAAD4AAAEAAQAAAgAAAAIDCVRyYW5z" +
    "Zm9ybQAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAADBw1TcHJpdGVUZXh0dXJlAAAAAAAAAAAAAAAAAAAAAQAAAA5TbGFzaFJlbmRlcmluZwAAAAABAAAAAlAwAAAAAAEA" +
    "AAAAAAAAAAAATUdGWA==";
  }
}
